name: Build and Push

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  build-push:
    uses: aserv92/libraries/.github/workflows/docker-build-push.yml@1.0.0
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
